// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
}
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '"YOUR_API_KEY_HERE"',
    appId: '1:1039187320593:android:0974fed67c137aca92b6b0',
    messagingSenderId: '1039187320593',
    projectId: 'free2b-b6221',
    storageBucket: 'free2b-b6221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '"YOUR_API_KEY_HERE"',
    appId: '1:1039187320593:ios:96d310387425b51e92b6b0',
    messagingSenderId: '1039187320593',
    projectId: 'free2b-b6221',
    storageBucket: 'free2b-b6221.appspot.com',
    androidClientId: '1039187320593-0fiiccvo4c62j8jli028j4fuplc14nk5.apps.googleusercontent.com',
    iosClientId: '1039187320593-gvkbmnec3h02tsshb9upl6fkk1h2ltd7.apps.googleusercontent.com',
    iosBundleId: 'com.free2bapp.mobile',
  );

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyABVZ6MAkbQLWyIuIyRPbtf6PbIAU2y-gY',
      appId: '1:1039187320593:web:1be9fd30c467226092b6b0',
      messagingSenderId: '1039187320593',
      projectId: 'free2b-b6221',
      authDomain: 'free2b-b6221.firebaseapp.com',
      storageBucket: 'free2b-b6221.appspot.com',
      measurementId: 'G-PE086NLZYX',
);
}
